### ISSUE TITLE
Add support for telemetry

### ISSUE THREAD

**Issue by kuper-adrian** [kuper-adrian/pubg-royale#1]
This api wrapper is still missing functions to poll the pubg api for telemetry data (see [here](https://documentation.pubg.com/en/telemetry.html)).

**Comment by 0c0de** [comment]
I will like to work on this feature

**Comment by kuper-adrian** [comment]
Great 😄 And thanks for contributing 👍

**Comment by 0c0de** [comment]
Done. Waiting your approval :smile:  :smiley:  :+1:

**Comment by kuper-adrian** [comment]
Closed thanks to pr #3, Thanks again for your time and help 👍
