### ISSUE TITLE
Add support for tournaments

### ISSUE THREAD

**Issue by kuper-adrian** [kuper-adrian/pubg-royale#2]
This api wrapper is still missing functions to poll the pubg api for tournament data (see [here](https://documentation.pubg.com/en/tournaments-endpoint.html)).

This one should be straightforward and not too much different from the existing api calls.

**Comment by Mera-Gangapersaud** [comment]
Hi, I'd like to try working in this.

**Comment by kuper-adrian** [comment]
Sure thing :D And thanks for contributing 👍

**Comment by kuper-adrian** [comment]
Closed through pr #6
