### ISSUE TITLE
Wrong URL format for pc-regions

### ISSUE THREAD

**Issue by kuper-adrian** [kuper-adrian/pubg-royale#4]
PUBG API v6.0.0 released October 3rd and changed the URL format for getting the season stats of any given player.

Old format:
```
https://api.pubg.com/shards/pc-{region}/players/{accountId}/seasons/{seasonId}
```

New format:
```
https://api.pubg.com/shards/{steam or kakao}/players/{accountId}/seasons/{seasonId}
```

More info on api v6.0.0 [here](https://forums.playbattlegrounds.com/topic/294431-version-600-is-live/).

Since pubg-royale still uses the old format, it only returns empty `gameModeStats` objects at the moment :disappointed: To fix this the `playerStats()` function must be adjusted to the new url format for every PC region (the XBOX regions still use the old format!).

Since its Hacktoberfest I will leave this issue up for grabs for some time for anyone interested in earning another pull request towards his awesome t-shirt :wink: 

This would also fix issue kuper-adrian/statg-bot#12 of the statg-discord-bot.

**Comment by alizhdanov** [comment]
Hey, how do you know whether it's steam or kakao? :-)

**Comment by kuper-adrian** [comment]
Good question :sweat_smile: Well at least the `pc-kakao` region should use `kakao` instead of `steam` but I don't really know if any of the other seasons do, sorry. I think it would be fine if only `pc-kakao` uses `kakao` for now. If other regions also need to use `kakao`, it could be fixed later.

**Comment by alizhdanov** [comment]
Ok, I'll do it then
